version: '3'

services:
  mongodb:
    image: mongo:5
    restart: always
    container_name: mongodb
    
    ports:
      - "27017:27017"
    
    environment:
      MONGODB_DATABASE: nest-pokemon
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    
    volumes:
      - ./mongo-data:/data/db

# volumes:
#   mongo-data:
#     driver: local